config/routes.rb
Rails.application.routes.draw do
  get 'tags/show'
  root "homes#top"
  get "about" => "homes#about"
  get 'search' => 'searchs#search'
  devise_for :users
  resources :users, only: [:show, :edit, :update]
  resources :logs, only: [:index, :show, :create, :edit, :update, :destroy]
  resources :recipes do
    resources :reviews, only: [:create, :destroy]
    resources :favorites, only: [:index, :create]
  end
  # get 'tag' => 'tags#show'
  resources :tags, only: [:show]
  delete "recipe/:recipe_id/favorite", to: "favorites#destroy", as: "recipe_favorite"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :recipe

  # ロード中に２度以上連続で登録しようとすることを防ぎます

  validates_uniqueness_of :user_id, scope: :recipe_id
end

app/models/log.rb
class Log < ApplicationRecord
  belongs_to :user
  enum record_status: { fine: 0, low: 1, sick: 2 }

  enum colour_status: { light_brown: 0, brown: 1, black: 2, orange: 3, green: 4 }

  enum shape_status: { big: 0, small: 1, hard: 2, soft: 3, water: 4 }

  def record_status_score
    if fine?
      5
    elsif low?
      3
    else
      0
    end
  end

  def colour_status_score
    if light_brown?
      5
    elsif brown?
      4
    elsif black?
      3
    elsif orange?
      2
    else
      1
    end
  end

  def shape_status_score
    if big?
      5
    elsif small?
      4
    elsif hard?
      3
    elsif soft?
      2
    else
      1
    end
  end
end

app/models/material.rb
class Material < ApplicationRecord
  belongs_to :recipe

  # バリデーション（材料を空の入力を防ぐ）
  validates :ingredient, presence: true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  # レシピ投稿画像 refile定義
  attachment :recipe_image
  
  
  # アソシエーション（親）
  belongs_to :user
  # アソシエーション（子）
  has_many :materials, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :reviews, dependent: :destroy
  ##多対多のアソシエーション
  has_many :recipe_tags, dependent: :destroy
  #中間テーブルであるrecipe_tagモデルを介してのtagモデルとの関連付けを記述
  has_many :tags, through: :recipe_tags
  
  
  # 複数のモデルを登録・更新させる
  accepts_nested_attributes_for :materials, allow_destroy: true


  # バリデーション（空の入力を防ぐ）
  validates :name, presence: true
  validates :description, presence: true
  validates :recipe_image, presence: true


  # favorited_by?(user)は既にブックマークしているかを検証します。
  def favorited_by?(user)
    favorites.where(user_id: user).exists?
  end
end

app/models/recipe_tag.rb
class RecipeTag < ApplicationRecord
  belongs_to :recipe
  belongs_to :tag
end

app/models/review.rb
class Review < ApplicationRecord
  attachment :review_image
  belongs_to :user
  belongs_to :recipe

  # バリデーション（コメントが空の入力を防ぐ）
  validates :comment, presence: true
end

app/models/tag.rb
class Tag < ApplicationRecord
  #多対多のアソシエーション
  has_many :recipe_tags, dependent: :destroy
  has_many :recipes, through: :recipe_tags
  #中間テーブルであるrecipe_tagモデルを介してのrecipeモデルとの関連付けを記述。

  attachment :tag_image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :profile_image
  has_many :logs, dependent: :destroy
  has_many :recipes, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :reviews, dependent: :destroy
  # バリデーション（名前：空を防ぐ、一意性があること、最低2文字、最高20字）
  validates :name, presence: true, uniqueness: true,
                   length: { minimum: 2, maximum: 20 }
  # （自己紹介：最高50字まで）
  validates :introduction, length: { maximum: 50 }
end

app/controllers/logs_controller.rb
class LogsController < ApplicationController
  before_action :authenticate_user!

  def index
    @log = Log.new
    @logs = current_user.logs
  end

  def create
    @log = Log.new(log_params)
    @log.save
    redirect_to logs_path
  end

  def show
    @log = Log.find(params[:id])
  end

  def edit
    @log = Log.find(params[:id])
    if @log.user != current_user
      redirect_to log_path(@log)
    end
  end

  def update
    @log = Log.find(params[:id])
    @log.update(log_params)
    redirect_to logs_path, notice: '変更が登録されました。'
  end

  def destroy
    @log = Log.find(params[:id])
    @log.destroy
    redirect_to logs_path
  end

  private

  def log_params
    params.require(:log).permit(:record_status, :user_id, :start_time, :colour_status, :shape_status).merge(user_id: current_user.id)
  end
end

app/controllers/searchs_controller.rb
class SearchsController < ApplicationController
  def search                              # form_withを設置しているviewからユーザーが検索を実行
    @value = params['search']['value']    # @valueにviewから送られてきた検索ワードを格納
    @how = params['search']['how']        # @howにviewから送られてきた検索方法(完全一致など)を格納
    @datas = search_for(@how,@value).page(params[:page]).per(5)       # search_forメソッドを実行(引数に検索ワードと検索方法)
  end
  
  private
  
  def match(value) 
    #valueに一致するカラムのデータをnameカラムから探し一致するもの全てを取得している。match(完全一致)メソッドが実施されて、その結果が@datasに格納される
    Recipe.where(name: value)
  end
  
  def forward(value) 
    Recipe.where("name LIKE ?", "#{value}%") #前方一致
  end
  
  def backward(value)
    Recipe.where("name LIKE ?", "%#{value}") #後方一致
  end
  
  def partical(value)
    Recipe.where("name LIKE ?", "%#{value}%") #部分一致
  end
  
  def search_for(how, value)
    case how               #case文でhowの中身が`'match'である場合serach_forメソッドの中でさらにmatchメソッドを呼んでいる。
    when 'match'                 
      match(value)
    when 'forward'
      forward(value)
    when 'backward'
      backward(value)
    when 'partical'
      partical(value)
    end
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def show
    @tag = Tag.find(params[:id])
    @recipes = @tag.recipes.all.includes([:user]).order(created_at: :desc).page(params[:page]).per(8)
  end
  private

  def tag_params
    params.require(:tag).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/logs_helper.rb
module LogsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/seraches_helper.rb
module SerachesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/searchs/search.html.erb
<div class="container-fluid">
  <div class="row mt-5">
      <% if @datas.empty?%>
      <div class="col-12 my-4 text-center">
        <h2>該当するレシピはありません</h2>
      </div>
      <% end %>
    <div class="col-12">
      <div class="texts-wrapper">
        <div class="contents-title text-center">
          <h4 class="my-1">ー検索結果ー</h4>
            <div class="row my-5">
              <div class="col-12">
                <div class="card-deck">
                  <% @datas.each do |data| %>
                    <div class="col-3 my-3">
                        <div class="card h-100">
                          <%= link_to recipe_path(data.id) do %>
                            <%= attachment_image_tag data, :recipe_image, :fill, 200, 200, class:"card-img-search"; %><br>
                          <% end %>
                          <div class="card-body">
                            <div class="row">
                              <div class="col-2">
                                <%= attachment_image_tag data.user, :profile_image,:fill, 60, 60, fallback: "no_image.jpg", class:"mt-3 rounded-circle" %>
                              </div>
                              <div class="col-10">
                                <p class="card-title">
                                  <%= link_to recipe_path(data.id) do %>
                                    <span><%= data.name %></span>
                                  <% end %>
                                </p>
                                <p class="card-text">
                                  <%= link_to user_path(data.user.id) do %>
                                    <span><i class="fas fa-user"></i><%= data.user.name %></span>
                                  <% end %>
                                </p>
                              </div>
                            </div>
                          </div>
                        </div>
                    </div>
                  <% end %>
                </div>
                <div class="m-5">
                  <%= paginate @datas %>
                </div>
              </div>
            </div>
        </div>
      </div>
    </div>
  </div>
</div>