config/routes.rb
Rails.application.routes.draw do
  get 'tags/show'
  root "homes#top"
  get "about" => "homes#about"
  get 'search' => 'searchs#search'
  devise_for :users
  resources :users, only: [:show, :edit, :update]
  resources :logs, only: [:index, :show, :create, :edit, :update, :destroy]
  resources :recipes do
    resources :reviews, only: [:create, :destroy]
    resources :favorites, only: [:index, :create]
  end
  # get 'tag' => 'tags#show'
  resources :tags, only: [:show]
  delete "recipe/:recipe_id/favorite", to: "favorites#destroy", as: "recipe_favorite"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :recipe

  # ロード中に２度以上連続で登録しようとすることを防ぎます

  validates_uniqueness_of :user_id, scope: :recipe_id
end

app/models/log.rb
class Log < ApplicationRecord
  belongs_to :user
  enum record_status: { fine: 0, low: 1, sick: 2 }

  enum colour_status: { light_brown: 0, brown: 1, black: 2, orange: 3, green: 4 }

  enum shape_status: { big: 0, small: 1, hard: 2, soft: 3, water: 4 }

  def record_status_score
    if fine?
      5
    elsif low?
      3
    else
      0
    end
  end

  def colour_status_score
    if light_brown?
      5
    elsif brown?
      4
    elsif black?
      3
    elsif orange?
      2
    else
      1
    end
  end

  def shape_status_score
    if big?
      5
    elsif small?
      4
    elsif hard?
      3
    elsif soft?
      2
    else
      1
    end
  end
end

app/models/material.rb
class Material < ApplicationRecord
  belongs_to :recipe

  # バリデーション（材料を空の入力を防ぐ）
  validates :ingredient, presence: true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  # レシピ投稿画像 refile定義
  attachment :recipe_image
  
  
  # アソシエーション（親）
  belongs_to :user
  # アソシエーション（子）
  has_many :materials, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :reviews, dependent: :destroy
  ##多対多のアソシエーション
  has_many :recipe_tags, dependent: :destroy
  #中間テーブルであるrecipe_tagモデルを介してのtagモデルとの関連付けを記述
  has_many :tags, through: :recipe_tags
  
  
  # 複数のモデルを登録・更新させる
  accepts_nested_attributes_for :materials, allow_destroy: true


  # バリデーション（空の入力を防ぐ）
  validates :name, presence: true
  validates :description, presence: true
  validates :recipe_image, presence: true


  # favorited_by?(user)は既にブックマークしているかを検証します。
  def favorited_by?(user)
    favorites.where(user_id: user).exists?
  end
end

app/models/recipe_tag.rb
class RecipeTag < ApplicationRecord
  belongs_to :recipe
  belongs_to :tag
end

app/models/review.rb
class Review < ApplicationRecord
  attachment :review_image
  belongs_to :user
  belongs_to :recipe

  # バリデーション（コメントが空の入力を防ぐ）
  validates :comment, presence: true
end

app/models/tag.rb
class Tag < ApplicationRecord
  #多対多のアソシエーション
  has_many :recipe_tags, dependent: :destroy
  has_many :recipes, through: :recipe_tags
  #中間テーブルであるrecipe_tagモデルを介してのrecipeモデルとの関連付けを記述。

  attachment :tag_image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :profile_image
  has_many :logs, dependent: :destroy
  has_many :recipes, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :reviews, dependent: :destroy
  # バリデーション（名前：空を防ぐ、一意性があること、最低2文字、最高20字）
  validates :name, presence: true, uniqueness: true,
                   length: { minimum: 2, maximum: 20 }
  # （自己紹介：最高50字まで）
  validates :introduction, length: { maximum: 50 }
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    @tags = Tag.all
    @recipes = Recipe.all.includes([:user]).order(created_at: :desc).limit(4)
    @recipe_ranks = Recipe.includes([:user]).find(Favorite.group(:recipe_id).order('count(recipe_id) desc').limit(4).pluck(:recipe_id))
  end
  
  def about
  end
end

app/controllers/logs_controller.rb
class LogsController < ApplicationController
  before_action :authenticate_user!

  def index
    @log = Log.new
    @logs = current_user.logs
  end

  def create
    @log = Log.new(log_params)
    @log.save
    redirect_to logs_path
  end

  def show
    @log = Log.find(params[:id])
  end

  def edit
    @log = Log.find(params[:id])
    if @log.user != current_user
      redirect_to log_path(@log)
    end
  end

  def update
    @log = Log.find(params[:id])
    @log.update(log_params)
    redirect_to logs_path, notice: '変更が登録されました。'
  end

  def destroy
    @log = Log.find(params[:id])
    @log.destroy
    redirect_to logs_path
  end

  private

  def log_params
    params.require(:log).permit(:record_status, :user_id, :start_time, :colour_status, :shape_status).merge(user_id: current_user.id)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index]
  def new
    @recipe = Recipe.new
    @recipe.materials.build # #親モデル.子モデル.buildで子モデルのインスタンス作成
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user_id = current_user.id
    if @recipe.save
      redirect_to recipe_path(@recipe.id)
    else
      flash.now[:alert] = '項目を正しくを入力してください。'
      render "new"
    end
  end

  def index
    @recipes = Recipe.all.includes([:user]).page(params[:page]).per(8)
  end

  def show
    @recipe = Recipe.find(params[:id])
    @review = Review.new
    @reviews = @recipe.reviews.all.includes([:user]).order(created_at: :desc).limit(10)
  end

  def edit
    @recipe = Recipe.find(params[:id])
    if @recipe.user != current_user
      redirect_to recipes_path
    end
  end

  def update
    @recipe = Recipe.find(params[:id])
    if @recipe.update(recipe_params)
      redirect_to recipe_path(@recipe.id), notice: '変更が登録されました。'
    else
      flash.now[:alert] = '項目を正しくを入力してください。'
      render "edit"
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy
    redirect_to recipes_path
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :count, :description, :work, :recipe_image, :user_id, materials_attributes: [:id, :ingredient, :amount, :_destroy],tag_ids: [])
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def show
    @tag = Tag.find(params[:id])
    @recipes = @tag.recipes.all.includes([:user]).order(created_at: :desc).page(params[:page]).per(8)
  end
  private

  def tag_params
    params.require(:tag).permit(:name)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = User.find(params[:id])
    @userrecipes = Recipe.where(user_id: @user.id)
    @recipes = Recipe.where(user_id: current_user).order(created_at: :desc).page(params[:page]).per(12)
    @favorites = Favorite.where(user_id: current_user.id).includes([:recipe])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id)
    else
      flash.now[:alert] = '名前を入力してください。'
      render "edit"
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :introduction, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/logs_helper.rb
module LogsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/seraches_helper.rb
module SerachesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/logs/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <div class="col-4 offset-4 text-center my-4">
      <h3 class="log-taitl">カレンダー</h3>
      </div>
        <div class="text-center my-5">
          <h4><strong>今日の腸の状態は？</strong></h4>
        </div>
        <div class="row form-group col-8 offset-3 my-4">
        <%= form_with model:@log, url:log_path, method: :patch, local:true do |f| %>
          <%= f.radio_button :record_status, :fine, {checked: true} %>
          <%= image_tag 'logo0.png', size: "150x100"%>

          <%= f.radio_button :record_status, :low , {} %>
          <%= image_tag 'logo1.png', size: "150x100"%>

          <%= f.radio_button :record_status, :sick, {} %>
          <%= image_tag 'logo3.png', size: "150x100"%></br>

          <%= f.label :日時, class: "time_date my-5" %>
            <%= f.datetime_select :start_time %>
          <div class="row form-group col-8 offset-3 my-4">
            <%= f.submit "登録", class: 'btn btn-outline-secondary col-5 offset-2' %>
          </div>
        <% end %>
        </div>
    </div>
  </div>
</div>

app/views/logs/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <div class="col-4 offset-4 text-center my-4">
      <h3 class="log-taitl">カレンダー</h3>
      </div>
        <div class="col-8 my-10">
          <h4><strong>今日の腸の状態は？</strong></h4>
        </div>
        <div class="row form-group col-12 my-4">
        <%= form_with model:@log, url:logs_path, method: :post, local:true do |f| %>
          <%= f.radio_button :record_status, :fine, {checked: true} %>
          <%= image_tag 'logo0.png', size: "150x100"%>

          <%= f.radio_button :record_status, :low , {} %>
          <%= image_tag 'logo1.png', size: "150x100"%>

          <%= f.radio_button :record_status, :sick, {} %>
          <%= image_tag 'logo3.png', size: "150x100"%></br>
    
            <!--カラー-->
          <%= f.radio_button :colour_status, :light_brown, {checked: true} %>
          <%= image_tag 'light_brown.png', size: "150x100"%>

          <%= f.radio_button :colour_status, :brown, {} %>
          <%= image_tag 'brown.png', size: "150x100"%>

          <%= f.radio_button :colour_status, :black, {} %>
          <%= image_tag 'black.png', size: "150x100"%>
          
          <%= f.radio_button :colour_status, :orange, {} %>
          <%= image_tag 'orange.png', size: "150x100"%>

          <%= f.radio_button :colour_status, :green, {} %>
          <%= image_tag 'green.png', size: "150x100"%></br>
          
          
          <!--形-->
           <%= f.radio_button :shape_status, :big, {checked: true} %>
          <%= image_tag 'big.png', size: "150x100"%>

          <%= f.radio_button :shape_status, :small, {} %>
          <%= image_tag 'small.png', size: "150x100"%>

          <%= f.radio_button :shape_status, :hard, {} %>
          <%= image_tag 'hard.png', size: "150x100"%>
          
          <%= f.radio_button :shape_status, :soft, {} %>
          <%= image_tag 'soft.png', size: "150x100"%>

          <%= f.radio_button :shape_status, :water, {} %>
          <%= image_tag 'water.png', size: "150x100"%></br>
          
          <%= f.label :日時, class: "time_date my-3" %>
          <%= f.datetime_select :start_time %>
            
          <%= f.submit "登録", class: 'btn btn-outline-secondary offset-10' %>
          <% end %>
        </div>
    </div>
  </div>
  <div class="calendar">
    <%= month_calendar events: @logs do |date, logs| %>
      <%= date.day %>
      <% logs.each do |log| %>
        <%= link_to log_path(log), class:"text-dark" do %>
          <% if log.record_status == "fine"  %>
            <div class="imag-status"><%= image_tag 'logo0.png', size: "150x100" %></div>
          <% elsif log.record_status == "low" %>
            <div class="imag-status"><%= image_tag 'logo1.png', size: "150x100"%></div>
          <% else %>
            <div class="imag-status"><%= image_tag 'logo3.png', size: "150x100" %></div>
          <% end %>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/logs/show.html.erb
<div class='container'>
  <div class="row">
    <div class="col-5 mt-4 offset-4">
      <h4><strong><%= current_user.name %>さん 今日の腸の調子は？</strong></h4>
    </div>
  </div>
  <div class="row">
    <div class="col-5 mt-4 offset-4">
      <div class"log-condition">
        <% if @log.fine?  %>
          <div class"imag-status"><%= image_tag 'logo0.png', size: "150x100", class:"col-5 offset-2" %></div>
          <h3 class="log-text my-4">その調子で頑張ろう！！</h3>
        <% elsif @log.low? %>
          <div class"imag-status"><%= image_tag 'logo1.png', size: "150x100", class:"col-5 offset-2"%></div>
          <h3 class="log-text my-4">おすすめレシピで綺麗習慣！</h3>
        <% else %>
          <div class"imag-status"><%= image_tag 'logo3.png', size: "150x100", class:"col-5 offset-2" %></div>
          <h3 class="log-text my-4">腸を温めて、休息をとろう！</h3>
        <% end %>
      </div>
      <div class"log-colour">
        <% if @log.light_brown?  %>
          <div class"imag-status"><%= image_tag 'light_brown.png', size: "150x100", class:"col-5 offset-2" %></div>
        <% elsif @log.brown? %>
          <div class"imag-status"><%= image_tag 'brown.png', size: "150x100", class:"col-5 offset-2"%></div>
        <% elsif @log.black? %>
          <div class"imag-status"><%= image_tag 'black.png', size: "150x100", class:"col-5 offset-2"%></div>
        <% elsif @log.orange? %>
          <div class"imag-status"><%= image_tag 'orange.png', size: "150x100", class:"col-5 offset-2"%></div>
        <% else %>
          <div class"imag-status"><%= image_tag 'green.png', size: "150x100", class:"col-5 offset-2" %></div>
        <% end %>
      </div>
      <div class"log-shape">
        <% if @log.big?  %>
          <div class"imag-status"><%= image_tag 'big.png', size: "150x100", class:"col-5 offset-2" %></div>
        <% elsif @log.small? %>
          <div class"imag-status"><%= image_tag 'small.png', size: "150x100", class:"col-5 offset-2"%></div>
        <% elsif @log.hard? %>
          <div class"imag-status"><%= image_tag 'hard.png', size: "150x100", class:"col-5 offset-2"%></div>
        <% elsif @log.soft? %>
          <div class"imag-status"><%= image_tag 'soft.png', size: "150x100", class:"col-5 offset-2"%></div>
        <% else %>
          <div class"imag-status"><%= image_tag 'water.png', size: "150x100", class:"col-5 offset-2" %></div>
        <% end %>
      </div>
      <p>
       <strong>時間</strong><%= @log.start_time.strftime("%Y-%m-%d %H:%M") %>
      </p>
    </div>
    <div class="col-5 mt-4 offset-4">
      <div class="link">
        <%= link_to '編集', edit_log_path(@log.id), class:"btn btn-outline-secondary col-3 offset-1" %>
        <%= link_to '削除', log_path(@log.id), method:  :delete, data: {confirm: "本当に削除しますか？"}, class:"btn btn-outline-danger col-3 offset-1" %>
      </div>
    </div>
    </div>
  </div>
</div>



<canvas id="myChart"></canvas>
<script>
var ctx = document.getElementById("myChart");
var myChart = new Chart(ctx, {
  type: 'radar',
  data: {
    labels: ["スッキリ感", "色", "形"],
    datasets: [
        {
        label: '今日の腸データ',
        backgroundColor: 'rgba(122,255,109,0.2)',
        borderColor: 'rgba(122,255,129,0.2)',
        data: [<%= @log.record_status_score %>, <%= @log.colour_status_score %>, <%= @log.shape_status_score %>]
        }
    ]
  },
  options: {
      scale: {
          ticks: {
              suggestedMin: 0,
              suggestedMax: 5
          }
      }
  }
});
</script>

app/views/recipes/_material_fields.html.erb
<div class="nested-fields">
  <div class="row form-group col-8 offset-2">
      <%= f.label :材料, class: "col-3" %>
      <%= f.text_field :ingredient, class: "col-4 form-control", placeholder: "材料" %>
      <%= f.text_field :amount, class: "form-control", placeholder: "分量",class:"offset-1 col-2" %>
    <div class="offset-1 col-1 px-0 w-auto">
      <%= link_to_remove_association "削除", f, class: "btn btn-secondary btn-block" %>
    </div>
  </div>
</div>

app/views/recipes/_reviews.html.erb
    <div class="texts-wrapper">
      <div class="contents-title text-center">
        <h4 class="review-taitl my-3">コメント<i class="fas fa-comment"></i><%= @recipe.reviews.count %>件</h4>
          <div class="row">
            <div class="col-12">
              <div class="recipe-reviews">
                  <%= render 'reviews/review', reviews: @reviews %>
              </div>
            </div>
          </div>
      </div>
    </div>
    <div class "row">
      <div class"col-12">
        <% if user_signed_in? %>
          <% if current_user.id != @recipe.user.id %>
            <div class="row my-5">
              <div class="col-8 offset-3">
                <div class="recipes-reviews">
                  <%= form_with(model: [@recipe, @review], id: "new-review") do |f| %>
                    <%= f.attachment_field :review_image, class: "imag-review" %>
                    <%= f.text_field :comment, class: "input-review" %>
                    <%= f.submit "コメントする", class: "submit-review", placeholder: "レビューここに記入しよう！" %>
                  <% end %>
                </div>
              </div>
            </div>
          <% else %>
          <% end %>
        <% end %>
      </div>
    </div>

app/views/recipes/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-4 offset-2 text-center">
      <% @recipe.tags.each do |tag| %>
       <%= link_to tag_path(tag), class: "tag_item" do %>
          <p class="tag_img"></p>
          <p class="tag_name btn btn-warning btn-sm">
           <%= tag.name %>
          </p>
        <% end %>
      <% end %>
    </div>
    <div class="col-4 ml-0">
      <p class="name my-3">
        <%= link_to user_path(@recipe.user.id),class:"link-recipe mr-3" do %>
          <span><i class="fas fa-user"></i><%= @recipe.user.name %></span>
        <% end %>
        <i class="mr-2">
          <%= link_to url: "#", class:"btn-social-icon-instagram" do %>
            <span class="btn-social-icon-instagram__square"><i class="fab fa-instagram fa-sm"></i></span>
          <% end %>
        </i>
        <i class="mr-3">
          <%= link_to url: "#", class:"btn-social-icon-twitter" do %>
            <span class="btn-social-icon-twitter__square"><i class="fab fa-twitter fa-sm"></i></span>
          <% end %>
        </i>
        <i class="mr-1">
          投稿日時：<%= @recipe.created_at.strftime('%Y/%m/%d') %>
        </i>
      </p>
    </div>
  </div>
  <div class="row">
    <div class="col-4 offset-2">
      <h4 class="recipe_name my-2"><%= @recipe.name %></h4>
      <div class="recipe_image my-2">
          <%= attachment_image_tag(@recipe, :recipe_image,:fill, 300, 300) %>
      </div>
    </div>
    <div class="col-4 ml-0">
        <div id="bookmark_<%= @recipe.id %>">
          <%= render "favorites/favorite", recipe: @recipe %>
        </div>
        <h6 class="recipe_title mt-3">レシピ説明</h6>
        <p class="recipe_work"><%= @recipe.work %></p>
        <% if user_signed_in? %>
          <% if current_user.id != @recipe.user.id %>
          <% else %>
          <div class="recipe-btn">
              <%= link_to "レシピ編集", edit_recipe_path(@recipe.id), class: "mr-3 btn btn-outline-success" %>
              <%= link_to "レシピ削除", recipe_path(@recipe.id), method:  :delete,data: {confirm: "本当に削除しますか？"}, class:  "btn btn-outline-danger" %>
          </div>
          <% end %>
        <% end %>
    </div>
  </div>
  <div class="row mt-5">
    <div class="col-5 offset-2">
      <div class="et_pb_module">
        <button id="fuu" class='secList'><h4>作り方</h4></button>
      </div>
    </div>
  </div>
  <div class="row mt-5">
      <div class="col-4 offset-2">
        <div class="fuu section">
         <table class="table table-hover table-inverse">
            <thead>
                <th>材料(<%= @recipe.count %>人分)</th>
                <th></th>
                <th colspan="3"></th>
            </thead>
            <tbody>
              <%@recipe.materials.each do |m|%>
              <tr>
                <td><%= m.ingredient %></td>
                <td><%= m.amount %></td>
              </tr>
              <%end%>
            </tbody>
          </table>
        </div>
      </div>
      <div class="col-4">
        <div class="fuu section">
          <table class="table table-hover table-inverse">
              <thead>
                  <th>作り方</th>
              </thead>
              <tbody>

                <tr>
                  <td><%= simple_format @recipe.description %></td>

                </tr>

              </tbody>
            </table>
        </div>
      </div>
  </div>
    <%= render 'reviews' %>
</div>

app/views/tags/show.html.erb
<div class="container-fluid">
  <div class="row mt-5">
    <div class="col-12">
      <div class="texts-wrapper">
        <div class="contents-title text-center">
          <h3 class="my-5">ー<%= @tag.name %>レシピー</h3>
          <% if @tag.recipes.count == 0 %>
            <div class="nill_recipe_view">
              <p class="recipe-count">
                <span><%= @tag.recipes.count %>件</span>
              </p>
              <p class="nill_recipe_count">
                <span><%= @tag.name %></span>
                のカテゴリーにはまだレシピが投稿されていません<br>
                このカテゴリーの投稿者の第１号になりませんか？<br>
                <%= link_to "レシピを投稿する", new_recipe_path, class: "btn btn-warning no_recipe_category_btn" %>
              </p>
            </div>
          <% else %>
           <p class="recipe-count">
             <span><%= @tag.recipes.count %></span>
              件のレシピがあります!!
            </p>
          <% end %>
            <div class="row my-5">
              <div class="col-12">
                <div class="card-deck">
                  <% @recipes.each do |recipe| %>
                    <div class="col-3 my-3">
                        <div class="card h-100">
                          <%= link_to recipe_path(recipe.id) do %>
                            <%= attachment_image_tag recipe, :recipe_image, :fill, 300, 300, class:"card-img-top"; %><br>
                          <% end %>
                          <div class="card-body">
                            <div class="row">
                              <div class="col-2">
                                <%= attachment_image_tag recipe.user, :profile_image,:fill, 60, 60, fallback: "no_image.jpg", class:"mt-3 rounded-circle"; %>
                              </div>
                              <div class="col-10">
                                <p class="card-title">
                                  <%= link_to recipe_path(recipe), class:"text-dark" do %>
                                    <span> <%= recipe.name %></span>
                                  <% end %>
                                </p>
                                <p class="card-text">
                                  <%= link_to user_path(recipe.user.id) do %>
                                    <span><i class="fas fa-user"></i><%= recipe.user.name %></span>
                                  <% end %>
                                </p>
                              </div>
                            </div>
                          </div>
                        </div>
                    </div>
                  <% end %>
                </div>
                <div class="m-5">
                  <%= paginate @recipes %>
                </div>
              </div>
            </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class='container'>
  <div class="row">
    <div class="col-12">
      <h2 class="row offset-5 my-5">マイページ編集</h2>
        <%= form_with model:@user, url:user_path, local:true do |f| %>
            <div class="row form-group col-8 offset-3">
              <%= f.label :画像, class: "col-lg-2 col-12" %>
              <%= f.attachment_field :profile_image %>
            </div>
            <div class="row form-group col-8 offset-3">
              <%= f.label :名前, class: "col-lg-2 col-12" %>
              <%= f.text_field :name, placeholder:"名前", class: 'col-lg-6 col-12 form-control' %>
            </div>
            <div class="row form-group col-8 offset-3">
              <%= f.label :自己紹介文, class: "col-lg-2 col-12" %>
              <%= f.text_field :introduction, placeholder:"レシピ説明", class: 'col-lg-6 col-12 form-control' %>
            </div>
            <div class="form-group">
              <%= f.submit "登録", class: 'user-botn btn btn-outline-secondary col-lg-2 col-8 offset-5' %>
            </div>
        <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<% if current_user != @user %>
<%= render 'user_recipes', user: @user, userrecipes: @userrecipes %>
<% else %>
<div class="wrap">
  <div class='container-fluid'>
    <ul id="tab-menu">
      <li><a href="#tab1" class="active">マイページ</a></li>
      <li><a href="#tab2" class="">投稿レシピ</a></li>
      <li><a href="#tab3" class="">保存レシピ</a></li>
    </ul>

    <div id="tab-contents">
      <div id="tab1" class="tab">
        <div class="row">
          <div class="col-lg-2 col-12 mt-4 offset-2">
            <%= attachment_image_tag @user, :profile_image, format:'jpeg', fallback:"no_image.jpg", class:"img-fluid mx-auto" %>
          </div>
          <div class="col-lg-5 col-12 offset-1 mt-4 mr-auto">
            <table class="table">
              <tr>
                <th>name</th>
                <th><%= @user.name %></th>
              </tr>
              <tr>
                <th>introduction</th>
                <th><%= @user.introduction %></th>
              </tr>
            </table>
            <div class="link-edit row offset-2">
              <%= link_to '編集', edit_user_path(@user.id), class:"btn btn_success" %>
            </div>
          </div>
        </div>
      </div>
              <!--投稿レシピ-->
      <div id="tab2" class="tab">
        <div class="row-fluid">
          <div class="col-lg-10 col-12 mt-4 offset-1">
            <div class="texts-wrapper">
              <div class="contents-title text-center">
                  <div class="d-flex flex-row flex-wrap">
                    <% @recipes.each do |recipe|%>
                      <div class="d-flex flex-column mx-2 mt-3">
                        <%= link_to recipe_path(recipe.id), class:"link_recipe" do %>
                          <%= attachment_image_tag recipe, :recipe_image, :fill, 120, 120, format:'jpeg', fallback:"no_image.jpg" %>
                        <% end %>
                        <p class="name">
                          <%= link_to recipe_path(recipe), class:"text-dark" do %>
                            <span> <%= recipe.name %></span>
                          <% end %>
                        </p>
                      </div>
                    <% end %>
                  </div>
              </div>
            </div>
          </div>
        </div>
      </div>
            <!--保存レシピ-->
      <div id="tab3" class="tab">
        <div class="row-fluid">
          <div class="col-lg-10 col-12 mt-4 offset-1">
            <div class="texts-wrapper">
              <div class="contents-title text-center">
                  <div class="d-flex flex-row flex-wrap">
                    <% @favorites.each do |favorite|%>
                      <div class="d-flex flex-column mx-2 mt-3">
                        <%= link_to recipe_path(favorite.recipe.id), class:"link_recipe" do %>
                          <%= attachment_image_tag favorite.recipe, :recipe_image, :fill, 120, 120, format:'jpeg', fallback:"no_image.jpg" %>
                        <% end %>
                        <p class="name">
                          <%= link_to recipe_path(favorite.recipe.id), class:"text-dark" do %>
                            <span> <%= favorite.recipe.name %></span>
                          <% end %>
                        </p>
                      </div>
                    <% end %>
                  </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<% end %>