config/routes.rb
Rails.application.routes.draw do
  get 'tags/show'
  root "homes#top"
  get "about" => "homes#about"
  get 'search' => 'searchs#search'
  devise_for :users
  resources :users, only: [:show, :edit, :update]
  resources :logs, only: [:index, :show, :create, :edit, :update, :destroy]
  resources :recipes do
    resources :reviews, only: [:create, :destroy]
    resources :favorites, only: [:index, :create]
  end
  # get 'tag' => 'tags#show'
  resources :tags, only: [:show]
  delete "recipe/:recipe_id/favorite", to: "favorites#destroy", as: "recipe_favorite"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :recipe

  # ロード中に２度以上連続で登録しようとすることを防ぎます

  validates_uniqueness_of :user_id, scope: :recipe_id
end

app/models/log.rb
class Log < ApplicationRecord
  belongs_to :user
  enum record_status: { fine: 0, low: 1, sick: 2 }

  enum colour_status: { light_brown: 0, brown: 1, black: 2, orange: 3, green: 4 }

  enum shape_status: { big: 0, small: 1, hard: 2, soft: 3, water: 4 }

  def record_status_score
    if fine?
      5
    elsif low?
      3
    else
      0
    end
  end

  def colour_status_score
    if light_brown?
      5
    elsif brown?
      4
    elsif black?
      3
    elsif orange?
      2
    else
      1
    end
  end

  def shape_status_score
    if big?
      5
    elsif small?
      4
    elsif hard?
      3
    elsif soft?
      2
    else
      1
    end
  end
end

app/models/material.rb
class Material < ApplicationRecord
  belongs_to :recipe

  # バリデーション（材料を空の入力を防ぐ）
  validates :ingredient, presence: true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  # レシピ投稿画像 refile定義
  attachment :recipe_image
  
  
  # アソシエーション（親）
  belongs_to :user
  # アソシエーション（子）
  has_many :materials, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :reviews, dependent: :destroy
  ##多対多のアソシエーション
  has_many :recipe_tags, dependent: :destroy
  #中間テーブルであるrecipe_tagモデルを介してのtagモデルとの関連付けを記述
  has_many :tags, through: :recipe_tags
  
  
  # 複数のモデルを登録・更新させる
  accepts_nested_attributes_for :materials, allow_destroy: true


  # バリデーション（空の入力を防ぐ）
  validates :name, presence: true
  validates :description, presence: true
  validates :recipe_image, presence: true


  # favorited_by?(user)は既にブックマークしているかを検証します。
  def favorited_by?(user)
    favorites.where(user_id: user).exists?
  end
end

app/models/recipe_tag.rb
class RecipeTag < ApplicationRecord
  belongs_to :recipe
  belongs_to :tag
end

app/models/review.rb
class Review < ApplicationRecord
  attachment :review_image
  belongs_to :user
  belongs_to :recipe

  # バリデーション（コメントが空の入力を防ぐ）
  validates :comment, presence: true
end

app/models/tag.rb
class Tag < ApplicationRecord
  #多対多のアソシエーション
  has_many :recipe_tags, dependent: :destroy
  has_many :recipes, through: :recipe_tags
  #中間テーブルであるrecipe_tagモデルを介してのrecipeモデルとの関連付けを記述。

  attachment :tag_image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :profile_image
  has_many :logs, dependent: :destroy
  has_many :recipes, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :reviews, dependent: :destroy
  # バリデーション（名前：空を防ぐ、一意性があること、最低2文字、最高20字）
  validates :name, presence: true, uniqueness: true,
                   length: { minimum: 2, maximum: 20 }
  # （自己紹介：最高50字まで）
  validates :introduction, length: { maximum: 50 }
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    @tags = Tag.all
    @recipes = Recipe.all.includes([:user]).order(created_at: :desc).limit(4)
    @recipe_ranks = Recipe.includes([:user]).find(Favorite.group(:recipe_id).order('count(recipe_id) desc').limit(4).pluck(:recipe_id))
  end
  
  def about
  end
end

app/controllers/logs_controller.rb
class LogsController < ApplicationController
  before_action :authenticate_user!

  def index
    @log = Log.new
    @logs = current_user.logs
  end

  def create
    @log = Log.new(log_params)
    @log.save
    redirect_to logs_path
  end

  def show
    @log = Log.find(params[:id])
  end

  def edit
    @log = Log.find(params[:id])
    if @log.user != current_user
      redirect_to log_path(@log)
    end
  end

  def update
    @log = Log.find(params[:id])
    @log.update(log_params)
    redirect_to logs_path, notice: '変更が登録されました。'
  end

  def destroy
    @log = Log.find(params[:id])
    @log.destroy
    redirect_to logs_path
  end

  private

  def log_params
    params.require(:log).permit(:record_status, :user_id, :start_time, :colour_status, :shape_status).merge(user_id: current_user.id)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index]

  def create
    review = Review.new(review_params)
    review.save
    @reviews = Recipe.find(params[:recipe_id]).reviews.all.includes([:user]).order(created_at: :desc).limit(10)
    # app/views/review/create.js.erbを参照する
  end

  def destroy
    @recipe = Recipe.find(params[:recipe_id])
    review = @recipe.reviews.find(params[:id])
    review.destroy
    @reviews = @recipe.reviews.all.includes([:user])
  end

  private

  def review_params
    params.require(:review).permit(:comment, :review_image).merge(user_id: current_user.id, recipe_id: params[:recipe_id])
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def show
    @tag = Tag.find(params[:id])
    @recipes = @tag.recipes.all.includes([:user]).order(created_at: :desc).page(params[:page]).per(8)
  end
  private

  def tag_params
    params.require(:tag).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/logs_helper.rb
module LogsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/seraches_helper.rb
module SerachesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/reviews/_review.html.erb
<ul class="thumbs-list">
  <div id="slider">
    <% reviews.each do |review| %>
      <li class="list-items recipe-review">
        <p>
          <%= attachment_image_tag review, :review_image, :fill, 200, 200, class:"card-img-review ml-5"; %>
        </p>
        <p class="recipe-title ml-3">
          <%= link_to user_path(review.user.id), class:"review-user-link" do %>
            <span><i class="fas fa-user"></i><%= review.user.name %></span>
          <% end%>
        </p>
        <p class="review-content ml-3">
          <%= review.comment %>
        </p>
        <p class="review-datetime ml-3">
          <%= review.created_at.strftime('%Y/%m/%d') %>
        <% if user_signed_in? %>
          <% if current_user.id != review.user_id %>
          <% else %>
            <%= link_to recipe_review_path(review.recipe_id, review.id), method: :delete, remote: true, class: "delete-review-link" do %>
              <i class="fas fa-trash"></i>
            <% end %>
          <% end %>
        <% end %>
        </p>
      </li>
    <% end %>
  </div>
</ul>


<script>
// 非同期通信を利用jqueryが読み込まれないためココに記載しました。
  $(function() {
    $('#slider').slideDown(1000);
    $('#slider').slick({
        dots: true, //スライドの下にドットのナビゲーションを表示
        autoplay: true,
        autoplaySpeed: 4000,
        arrows: true,
        slidesToShow: 4, //表示するスライドの数
        slidesToScroll: 4, //スクロールで切り替わるスライドの数

        //レスポンシブ対応させたい場合は以下も記述
        responsive: [{
          breakpoint: 768, //画面幅768pxで以下のセッティング
          settings: {
            slidesToShow: 4,
            slidesToScroll: 4,
          }
        }]
    });
  });
</script>

app/views/reviews/create.js.erb
$(".recipe-reviews").html("<%= j(render 'reviews/review', reviews: @reviews) %>");
$("#review_comment").val("");

app/views/reviews/destroy.js.erb
$(".recipe-reviews").html("<%= j(render 'reviews/review', reviews: @reviews) %>");
$("#review_comment").val("");