config/routes.rb
Rails.application.routes.draw do
  get 'tags/show'
  root "homes#top"
  get "about" => "homes#about"
  get 'search' => 'searchs#search'
  devise_for :users
  resources :users, only: [:show, :edit, :update]
  resources :logs, only: [:index, :show, :create, :edit, :update, :destroy]
  resources :recipes do
    resources :reviews, only: [:create, :destroy]
    resources :favorites, only: [:index, :create]
  end
  # get 'tag' => 'tags#show'
  resources :tags, only: [:show]
  delete "recipe/:recipe_id/favorite", to: "favorites#destroy", as: "recipe_favorite"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :recipe

  # ロード中に２度以上連続で登録しようとすることを防ぎます

  validates_uniqueness_of :user_id, scope: :recipe_id
end

app/models/log.rb
class Log < ApplicationRecord
  belongs_to :user
  enum record_status: { fine: 0, low: 1, sick: 2 }

  enum colour_status: { light_brown: 0, brown: 1, black: 2, orange: 3, green: 4 }

  enum shape_status: { big: 0, small: 1, hard: 2, soft: 3, water: 4 }

  def record_status_score
    if fine?
      5
    elsif low?
      3
    else
      0
    end
  end

  def colour_status_score
    if light_brown?
      5
    elsif brown?
      4
    elsif black?
      3
    elsif orange?
      2
    else
      1
    end
  end

  def shape_status_score
    if big?
      5
    elsif small?
      4
    elsif hard?
      3
    elsif soft?
      2
    else
      1
    end
  end
end

app/models/material.rb
class Material < ApplicationRecord
  belongs_to :recipe

  # バリデーション（材料を空の入力を防ぐ）
  validates :ingredient, presence: true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  # レシピ投稿画像 refile定義
  attachment :recipe_image
  
  
  # アソシエーション（親）
  belongs_to :user
  # アソシエーション（子）
  has_many :materials, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :reviews, dependent: :destroy
  ##多対多のアソシエーション
  has_many :recipe_tags, dependent: :destroy
  #中間テーブルであるrecipe_tagモデルを介してのtagモデルとの関連付けを記述
  has_many :tags, through: :recipe_tags
  
  
  # 複数のモデルを登録・更新させる
  accepts_nested_attributes_for :materials, allow_destroy: true


  # バリデーション（空の入力を防ぐ）
  validates :name, presence: true
  validates :description, presence: true
  validates :recipe_image, presence: true


  # favorited_by?(user)は既にブックマークしているかを検証します。
  def favorited_by?(user)
    favorites.where(user_id: user).exists?
  end
end

app/models/recipe_tag.rb
class RecipeTag < ApplicationRecord
  belongs_to :recipe
  belongs_to :tag
end

app/models/review.rb
class Review < ApplicationRecord
  attachment :review_image
  belongs_to :user
  belongs_to :recipe

  # バリデーション（コメントが空の入力を防ぐ）
  validates :comment, presence: true
end

app/models/tag.rb
class Tag < ApplicationRecord
  #多対多のアソシエーション
  has_many :recipe_tags, dependent: :destroy
  has_many :recipes, through: :recipe_tags
  #中間テーブルであるrecipe_tagモデルを介してのrecipeモデルとの関連付けを記述。

  attachment :tag_image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :profile_image
  has_many :logs, dependent: :destroy
  has_many :recipes, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :reviews, dependent: :destroy
  # バリデーション（名前：空を防ぐ、一意性があること、最低2文字、最高20字）
  validates :name, presence: true, uniqueness: true,
                   length: { minimum: 2, maximum: 20 }
  # （自己紹介：最高50字まで）
  validates :introduction, length: { maximum: 50 }
end

app/controllers/logs_controller.rb
class LogsController < ApplicationController
  before_action :authenticate_user!

  def index
    @log = Log.new
    @logs = current_user.logs
  end

  def create
    @log = Log.new(log_params)
    @log.save
    redirect_to logs_path
  end

  def show
    @log = Log.find(params[:id])
  end

  def edit
    @log = Log.find(params[:id])
    if @log.user != current_user
      redirect_to log_path(@log)
    end
  end

  def update
    @log = Log.find(params[:id])
    @log.update(log_params)
    redirect_to logs_path, notice: '変更が登録されました。'
  end

  def destroy
    @log = Log.find(params[:id])
    @log.destroy
    redirect_to logs_path
  end

  private

  def log_params
    params.require(:log).permit(:record_status, :user_id, :start_time, :colour_status, :shape_status).merge(user_id: current_user.id)
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def show
    @tag = Tag.find(params[:id])
    @recipes = @tag.recipes.all.includes([:user]).order(created_at: :desc).page(params[:page]).per(8)
  end
  private

  def tag_params
    params.require(:tag).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/logs_helper.rb
module LogsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/seraches_helper.rb
module SerachesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chokatsu</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick-theme.css"/>


    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>


    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no, minimum-scale=1.0">
    
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0/dist/Chart.min.js"></script>
  </head>

  <body>
    <header class="header">
      <nav class="navbar navbar-expand-lg navbar-light" >
        <div class="container">
          <div>
            <%= link_to root_path, class: "navbar-brand", local: true do %>
            <h5 class="lo">chokatsu recipe</h5>
            <% end %>
          </div>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse flex-column" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
               <% if user_signed_in? %>
                <div class="mt-1 mr-5"><strong>ようこそ、<%= current_user.name %>さん！</strong></div>
                <li class="nav-item mr-1"><%= link_to "about", about_path, class: "nav-link " %></li>
                <li class="nav-item mr-1"><%= link_to "マイページ", user_path(current_user.id), class: "nav-link " %></li>
                <li class="nav-item mr-1"><%= link_to "レシピ一覧", recipes_path, class: "nav-link " %></li>
                <li class="nav-item mr-1"><%= link_to "レシピ投稿", new_recipe_path, class: "nav-link " %></li>
                <li class="nav-item mr-1 "><%= link_to "ログ", logs_path, class: "nav-link " %></li>
                <li class="nav-item mr-1"><%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "nav-link " %></li>
              <% else %>
                <li class="nav-item mr-1"><%= link_to "レシピ一覧", recipes_path, class: "nav-link " %></li>
                <li class="nav-item mr-1"><%= link_to "新規登録", new_user_registration_path, class: "nav-link " %></li>
                <li class="nav-item mr-1"><%= link_to "ログイン", new_user_session_path, class: "nav-link " %></li>
              <% end %>
            </ul>
            <div class="row ml-auto mr-1">
              <%= form_with url: search_path, method: :get, class: "search form-inline", local: true do |f| %>
                <%= f.text_field 'search[value]', placeholder:"レシピ検索", class: "search_form" %>
                <%= f.hidden_field 'search[how]', value: "partical" %>
                <%= f.submit "検索", class: "btn" %>
              <% end %>
            </div>
          </div>
        </div>
      </nav>
    </header>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
    <footer>
       <div class="container mt-5">
  	     <div class="row">
    	     <div class="mx-auto">
    		     <p>©chokatsu recipe</p>
    	     </div>
        </div>
       </div>
     </footer>
  </body>
</html>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: '先月'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: '来月'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %></span>
    <% else %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %> - <%= calendar.end_week %></span>
    <% end %>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>